### ISSUE TITLE
Option list empty

### ISSUE THREAD

**Issue by UnbreakableKid** [notsapinho/powercord-together#11]
After today's fix the button has reappeared but there are no options to pick (tested also without theme)

![image](https://user-images.githubusercontent.com/29483407/134050468-de2c6d4c-a8c4-48ce-9f66-7e3357e9fc80.png)

![image](https://user-images.githubusercontent.com/29483407/134050286-14914f82-c870-4b59-84cb-0402c6f6b575.png)

**Comment by notsapinho** [comment]
fixed
