### ISSUE TITLE
Doodle Crew has been moved to Sketch Heads

### ISSUE THREAD

**Issue by Lock-The-Door** [notsapinho/powercord-together#16]
![image](https://user-images.githubusercontent.com/49077851/151437176-32360b38-cd4a-4ae6-87cf-f69aa54d8a68.png)

**Comment by Lock-The-Door** [comment]
I created #17 which will add sketch heads (and change a few other things as well in the games list)

**Comment by notsapinho** [comment]
Fixed in #17
