### ISSUE TITLE
[Bug] Since the last update many games have disappeared

### ISSUE THREAD

**Issue by AngelAsukii** [notsapinho/powercord-together#18]
Here is the current catalog, while an update or two before, there were many more games available

![image_2022-02-07_102513](https://user-images.githubusercontent.com/42059981/152760830-f6800771-c63f-49e6-b940-d83cc7dd2c24.png)

**Comment by Lock-The-Door** [comment]
That's due to discord boost locking some activities.
The only servers that can still access these games without boost are the ones that had early access.
