### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by RaspberryKitty1** [notsapinho/powercord-together#19]
dont know if this is still maintained or not but it no longer works with discord Stable 125308 (7245591)

**Comment by Lock-The-Door** [comment]
I believe a recent discord update shifted around some stuff which broke a bunch of plugins and probably this one too.

**Comment by Davoleo** [comment]
Can confirm, here's the error log screenshot
![powercord-together_error](https://user-images.githubusercontent.com/24458276/164934097-0555457d-7449-42c7-872c-6029386e89dc.png)

**Comment by notsapinho** [comment]
I'm not at home rn so there isn't much I can do, going to fix this on Monday, but be free to PR a fix.

**Comment by Shironep** [comment]
> I'm not at home rn so there isn't much I can do, going to fix this on Monday, but be free to PR a fix.

Did you manage to fix this?

**Comment by notsapinho** [comment]
Finally fixed -> 7b44c0a
