### ISSUE TITLE
How can you invite your friends to watch it?

### ISSUE THREAD

**Issue by Legend82825** [notsapinho/powercord-together#9]
when my friends join the vc, they cant see anything for joining youtube together.

**Comment by notsapinho** [comment]
They need to click on the voice channel and then a button "Join Activity" should appear on the screen

**Comment by Legend82825** [comment]
> 
> 
> They need to click on the voice channel and then a button "Join Activity" should appear on the screen

i tried it with my alt, but sadly, there isn't any button like that.

**Comment by notsapinho** [comment]
u trying to join on desktop app or web?

**Comment by Legend82825** [comment]
discord stable app.

**Comment by notsapinho** [comment]
weird, add me on discord so we can test together notsapinho#2975

**Comment by Legend82825** [comment]
oh, okay

**Comment by notsapinho** [comment]
New advice added on the README
